// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKJe2lriXOLn4iOkMmeLE4g69Cz-5GQao',
    appId: '1:694203736616:web:a9f94ae301bfa94241cb1d',
    messagingSenderId: '694203736616',
    projectId: 'campo-valor',
    authDomain: 'campo-valor.firebaseapp.com',
    storageBucket: 'campo-valor.firebasestorage.app',
    measurementId: 'G-3PRWNSRQTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBTG5KTOm7TNbzd2eeko1VFZzNDeVIXA',
    appId: '1:694203736616:android:139097763b57b5e541cb1d',
    messagingSenderId: '694203736616',
    projectId: 'campo-valor',
    storageBucket: 'campo-valor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeoFBYk-aN35sRb862SGQ-njbiarNGuJI',
    appId: '1:694203736616:ios:3f31f04e8c627a7141cb1d',
    messagingSenderId: '694203736616',
    projectId: 'campo-valor',
    storageBucket: 'campo-valor.firebasestorage.app',
    iosBundleId: 'com.example.appcampo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeoFBYk-aN35sRb862SGQ-njbiarNGuJI',
    appId: '1:694203736616:ios:3f31f04e8c627a7141cb1d',
    messagingSenderId: '694203736616',
    projectId: 'campo-valor',
    storageBucket: 'campo-valor.firebasestorage.app',
    iosBundleId: 'com.example.appcampo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKJe2lriXOLn4iOkMmeLE4g69Cz-5GQao',
    appId: '1:694203736616:web:8e9b4ead439ee33741cb1d',
    messagingSenderId: '694203736616',
    projectId: 'campo-valor',
    authDomain: 'campo-valor.firebaseapp.com',
    storageBucket: 'campo-valor.firebasestorage.app',
    measurementId: 'G-0JCZJ0DNF8',
  );
}
